package database.local;

import database.MovieDatabaseInterface;
import entity.Entity;
import entity.Rating;
import entity.builder.EntityBuilder;
import entity.builder.FingerprintBuilder;
import entity.builder.MovieBuilder;
import lombok.Value;

import java.util.ArrayList;
import java.util.List;

@Value
public class LocalDatabase implements MovieDatabaseInterface {
    static List<Entity> entities;
    @Override
    public List<Entity> getAllMovies() {
        load();
        return entities;
    }
    private static void load(){
        entities = new ArrayList<>();

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(99).recension("a masterpiece").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(1)
                        .HAPPY(3)
                        .HORROR(6)
                        .ACTION(1)
                        .ART(10)
                        .LOVE(0)
                        .COMEDY(2)
                        .FANTASY(8)
                        .EXPERIENCE(10)
                        .STORY(7)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(62).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(97).recension("Machines are coming").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(4)
                        .HAPPY(6)
                        .HORROR(7)
                        .ACTION(5)
                        .ART(7)
                        .LOVE(8)
                        .COMEDY(5)
                        .FANTASY(7)
                        .EXPERIENCE(7)
                        .STORY(8)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(264660).build().generate()).build().generate());
        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(96).recension("Asian stuff").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(5)
                        .HAPPY(5)
                        .HORROR(8)
                        .ACTION(3)
                        .ART(9)
                        .LOVE(4)
                        .COMEDY(7)
                        .FANTASY(1)
                        .EXPERIENCE(8)
                        .STORY(7)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(496243).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(95).recension("inversive Horror").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(3)
                        .HAPPY(1)
                        .HORROR(9)
                        .ACTION(0)
                        .ART(9)
                        .LOVE(7)
                        .COMEDY(3)
                        .FANTASY(3)
                        .EXPERIENCE(9)
                        .STORY(6)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(500840).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(95).recension("truly scary").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(7)
                        .HAPPY(1)
                        .HORROR(10)
                        .ACTION(3)
                        .ART(8)
                        .LOVE(0)
                        .COMEDY(1)
                        .FANTASY(0)
                        .EXPERIENCE(10)
                        .STORY(6)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(493922).build().generate()).build().generate());
        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(94).recension("dreamy zombies").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(7)
                        .HAPPY(6)
                        .HORROR(7)
                        .ACTION(7)
                        .ART(7)
                        .LOVE(5)
                        .COMEDY(3)
                        .FANTASY(2)
                        .EXPERIENCE(8)
                        .STORY(5)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(170).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(96).recension("comic made right").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(0)
                        .HAPPY(7)
                        .HORROR(0)
                        .ACTION(8)
                        .ART(6)
                        .LOVE(9)
                        .COMEDY(9)
                        .FANTASY(6)
                        .EXPERIENCE(5)
                        .STORY(7)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(22538).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(92).recension("frightening").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(9)
                        .HAPPY(1)
                        .HORROR(9)
                        .ACTION(0)
                        .ART(10)
                        .LOVE(6)
                        .COMEDY(0)
                        .FANTASY(2)
                        .EXPERIENCE(7)
                        .STORY(4)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(17609).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(80).recension("early Kaufmann").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(0)
                        .HAPPY(7)
                        .HORROR(4)
                        .ACTION(2)
                        .ART(7)
                        .LOVE(9)
                        .COMEDY(6)
                        .FANTASY(3)
                        .EXPERIENCE(6)
                        .STORY(5)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(38).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(86).recension("Found Footage Zombies!").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(8)
                        .HAPPY(1)
                        .HORROR(8)
                        .ACTION(5)
                        .ART(4)
                        .LOVE(0)
                        .COMEDY(1)
                        .FANTASY(0)
                        .EXPERIENCE(7)
                        .STORY(2)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(8329).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(86).recension("pure sadness").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(2)
                        .HAPPY(0)
                        .HORROR(5)
                        .ACTION(1)
                        .ART(8)
                        .LOVE(4)
                        .COMEDY(2)
                        .FANTASY(3)
                        .EXPERIENCE(7)
                        .STORY(4)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(62215).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(85).recension("avongade love").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(0)
                        .HAPPY(4)
                        .HORROR(0)
                        .ACTION(0)
                        .ART(6)
                        .LOVE(9)
                        .COMEDY(5)
                        .FANTASY(0)
                        .EXPERIENCE(6)
                        .STORY(6)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(19913).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(85).recension("a skandal movie, but also a good one").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(1)
                        .HAPPY(5)
                        .HORROR(0)
                        .ACTION(1)
                        .ART(7)
                        .LOVE(8)
                        .COMEDY(9)
                        .FANTASY(0)
                        .EXPERIENCE(4)
                        .STORY(6)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(802).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(87).recension("a experience like none other").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(10)
                        .HAPPY(5)
                        .HORROR(8)
                        .ACTION(8)
                        .ART(9)
                        .LOVE(4)
                        .COMEDY(8)
                        .FANTASY(6)
                        .EXPERIENCE(10)
                        .STORY(3)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(460885).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(87).recension("a original thriller").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(3)
                        .HAPPY(3)
                        .HORROR(6)
                        .ACTION(8)
                        .ART(7)
                        .LOVE(3)
                        .COMEDY(2)
                        .FANTASY(0)
                        .EXPERIENCE(8)
                        .STORY(9)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(103663).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(92).recension("love can be a disaster").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(1)
                        .HAPPY(6)
                        .HORROR(4)
                        .ACTION(4)
                        .ART(8)
                        .LOVE(7)
                        .COMEDY(3)
                        .FANTASY(1)
                        .EXPERIENCE(8)
                        .STORY(7)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(345).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(86).recension("Tarkowsky in a horror movie").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(7)
                        .HAPPY(3)
                        .HORROR(8)
                        .ACTION(5)
                        .ART(7)
                        .LOVE(4)
                        .COMEDY(2)
                        .FANTASY(2)
                        .EXPERIENCE(8)
                        .STORY(3)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(2291).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(90).recension("the best animation ever made").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(0)
                        .HAPPY(7)
                        .HORROR(1)
                        .ACTION(7)
                        .ART(5)
                        .LOVE(9)
                        .COMEDY(7)
                        .FANTASY(7)
                        .EXPERIENCE(4)
                        .STORY(7)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(10681).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(91).recension("touching nihilism or not?").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(1)
                        .HAPPY(1)
                        .HORROR(5)
                        .ACTION(0)
                        .ART(9)
                        .LOVE(7)
                        .COMEDY(0)
                        .FANTASY(2)
                        .EXPERIENCE(8)
                        .STORY(4)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(428449).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(91).recension("never seen before fears").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(5)
                        .HAPPY(1)
                        .HORROR(4)
                        .ACTION(0)
                        .ART(9)
                        .LOVE(1)
                        .COMEDY(1)
                        .FANTASY(0)
                        .EXPERIENCE(8)
                        .STORY(5)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(71859).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(87).recension("pure Imagination from Tim Burton").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(1)
                        .HAPPY(9)
                        .HORROR(1)
                        .ACTION(2)
                        .ART(6)
                        .LOVE(5)
                        .COMEDY(6)
                        .FANTASY(10)
                        .EXPERIENCE(5)
                        .STORY(9)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(587).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(86).recension("maybe time is a concept").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(5)
                        .HAPPY(5)
                        .HORROR(4)
                        .ACTION(6)
                        .ART(4)
                        .LOVE(4)
                        .COMEDY(5)
                        .FANTASY(0)
                        .EXPERIENCE(7)
                        .STORY(7)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(77).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(86).recension("a movie about a very funny, different world").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(4)
                        .HAPPY(6)
                        .HORROR(4)
                        .ACTION(3)
                        .ART(8)
                        .LOVE(7)
                        .COMEDY(10)
                        .FANTASY(3)
                        .EXPERIENCE(7)
                        .STORY(5)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(254320).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(86).recension("a movie for every Pokemon Fan").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(1)
                        .HAPPY(8)
                        .HORROR(1)
                        .ACTION(7)
                        .ART(1)
                        .LOVE(5)
                        .COMEDY(8)
                        .FANTASY(10)
                        .EXPERIENCE(0)
                        .STORY(1)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(447404).build().generate()).build().generate());


        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(89).recension("a film that goes under the skin").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(7)
                        .HAPPY(2)
                        .HORROR(8)
                        .ACTION(4)
                        .ART(9)
                        .LOVE(2)
                        .COMEDY(1)
                        .FANTASY(0)
                        .EXPERIENCE(9)
                        .STORY(7)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(10494).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(82).recension("a dreamy arthouse").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(1)
                        .HAPPY(10)
                        .HORROR(0)
                        .ACTION(0)
                        .ART(8)
                        .LOVE(6)
                        .COMEDY(5)
                        .FANTASY(3)
                        .EXPERIENCE(6)
                        .STORY(7)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(194).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(85).recension("make your own choice, to go the same way").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(2)
                        .HAPPY(4)
                        .HORROR(6)
                        .ACTION(2)
                        .ART(5)
                        .LOVE(0)
                        .COMEDY(4)
                        .FANTASY(3)
                        .EXPERIENCE(9)
                        .STORY(9)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(569547).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(91).recension("the sadest movie ever made").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(1)
                        .HAPPY(0)
                        .HORROR(4)
                        .ACTION(0)
                        .ART(10)
                        .LOVE(6)
                        .COMEDY(7)
                        .FANTASY(3)
                        .EXPERIENCE(9)
                        .STORY(7)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(4960).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(92).recension("welcome to the 21 centry").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(4)
                        .HAPPY(5)
                        .HORROR(3)
                        .ACTION(3)
                        .ART(6)
                        .LOVE(5)
                        .COMEDY(3)
                        .FANTASY(0)
                        .EXPERIENCE(6)
                        .STORY(9)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(550).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(90).recension("pure emotion").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(1)
                        .HAPPY(5)
                        .HORROR(1)
                        .ACTION(1)
                        .ART(1)
                        .LOVE(1)
                        .COMEDY(4)
                        .FANTASY(0)
                        .EXPERIENCE(6)
                        .STORY(9)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(235).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(90).recension("safacating").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(5)
                        .HAPPY(2)
                        .HORROR(7)
                        .ACTION(2)
                        .ART(8)
                        .LOVE(4)
                        .COMEDY(6)
                        .FANTASY(2)
                        .EXPERIENCE(9)
                        .STORY(1)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(381283).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(90).recension("Nolans best").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(5)
                        .HAPPY(6)
                        .HORROR(4)
                        .ACTION(6)
                        .ART(5)
                        .LOVE(2)
                        .COMEDY(1)
                        .FANTASY(4)
                        .EXPERIENCE(5)
                        .STORY(7)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(157336).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(89).recension("'Who did it?' at its best").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(3)
                        .HAPPY(7)
                        .HORROR(3)
                        .ACTION(6)
                        .ART(4)
                        .LOVE(2)
                        .COMEDY(7)
                        .FANTASY(0)
                        .EXPERIENCE(3)
                        .STORY(9)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(546554).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(86).recension("The Room - Origin Story").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(0)
                        .HAPPY(7)
                        .HORROR(0)
                        .ACTION(0)
                        .ART(3)
                        .LOVE(3)
                        .COMEDY(9)
                        .FANTASY(0)
                        .EXPERIENCE(2)
                        .STORY(7)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(371638).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(86).recension("a unique Story, thats not just love").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(0)
                        .HAPPY(6)
                        .HORROR(0)
                        .ACTION(0)
                        .ART(6)
                        .LOVE(9)
                        .COMEDY(3)
                        .FANTASY(0)
                        .EXPERIENCE(7)
                        .STORY(8)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(153).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(85).recension("splatter done wrong").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(9)
                        .HAPPY(3)
                        .HORROR(7)
                        .ACTION(7)
                        .ART(5)
                        .LOVE(1)
                        .COMEDY(5)
                        .FANTASY(0)
                        .EXPERIENCE(4)
                        .STORY(4)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(313922).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(80).recension("a guide to funny horror").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(7)
                        .HAPPY(8)
                        .HORROR(3)
                        .ACTION(8)
                        .ART(3)
                        .LOVE(3)
                        .COMEDY(8)
                        .FANTASY(0)
                        .EXPERIENCE(4)
                        .STORY(4)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(19908).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(77).recension("fun watch with friends").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(2)
                        .HAPPY(4)
                        .HORROR(5)
                        .ACTION(0)
                        .ART(4)
                        .LOVE(0)
                        .COMEDY(1)
                        .FANTASY(2)
                        .EXPERIENCE(8)
                        .STORY(1)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(335866).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(79).recension("femism in 1950s").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(4)
                        .HAPPY(3)
                        .HORROR(7)
                        .ACTION(1)
                        .ART(6)
                        .LOVE(3)
                        .COMEDY(3)
                        .FANTASY(1)
                        .EXPERIENCE(7)
                        .STORY(2)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(11481).build().generate()).build().generate());

        entities.add(EntityBuilder.builder()
                .RATING(Rating.builder().rating(85).recension("social critic with Joker").build())
                .FINGERPRINT(FingerprintBuilder.builder()
                        .BLOOD(5)
                        .HAPPY(6)
                        .HORROR(4)
                        .ACTION(5)
                        .ART(3)
                        .LOVE(3)
                        .COMEDY(6)
                        .FANTASY(0)
                        .EXPERIENCE(7)
                        .STORY(6)
                        .build().generate())
                .MOVIE(MovieBuilder.builder().movieId(475557).build().generate()).build().generate());

    }
}
